export const THEME_OPTIONS = [
  {
    value: 'light',
    label: 'Paper',
    description: 'Clean daylight surfaces with crisp blue accents.',
    swatch: ['#f8fafc', '#2563eb', '#06b6d4'],
  },
  {
    value: 'dark',
    label: 'Midnight',
    description: 'Deep neutral UI with cool cyan focus states.',
    swatch: ['#070a13', '#7dd3fc', '#a78bfa'],
  },
  {
    value: 'signature',
    label: 'QueryCraft',
    description: 'The teal and blue brand palette for daily work.',
    swatch: ['#061815', '#2dd4bf', '#38bdf8'],
  },
  {
    value: 'crimson',
    label: 'Crimson',
    description: 'Dark wine surfaces with rose and ember accents.',
    swatch: ['#18070d', '#fb7185', '#f97316'],
  },
  {
    value: 'aurora',
    label: 'Aurora',
    description: 'Forest green depth with soft cyan highlights.',
    swatch: ['#041811', '#34d399', '#22d3ee'],
  },
  {
    value: 'electric-night',
    label: 'Electric Night',
    description: 'Late-night violet with controlled neon pink.',
    swatch: ['#0a0718', '#c084fc', '#f472b6'],
  },
] as const;

export type ThemeMode = (typeof THEME_OPTIONS)[number]['value'];
export type ResolvedAppearance = 'light' | 'dark';

type ToneScale = {
  emerald: string;
  violet: string;
  cyan: string;
  fuchsia: string;
  sky: string;
  amber: string;
  rose: string;
};

type ThemePalette = {
  appearance: ResolvedAppearance;
  background: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  border: string;
  card: string;
  cardForeground: string;
  ring: string;
  surface: string;
  surfaceSoft: string;
  surfaceStrong: string;
  surfaceElevated: string;
  surfaceHover: string;
  surfaceActive: string;
  sidebar: string;
  topbar: string;
  navActive: string;
  navActiveForeground: string;
  overlay: string;
  shadowColor: string;
  brandFrom: string;
  brandTo: string;
  brandText: string;
  success: string;
  successForeground: string;
  danger: string;
  dangerForeground: string;
  warning: string;
  info: string;
  editorBg: string;
  editorBg2: string;
  editorGutter: string;
  tones: ToneScale;
};

const palette: Record<ThemeMode, ThemePalette> = {
  light: {
    appearance: 'light',
    background: '#f8fafc',
    foreground: '#101827',
    muted: '#eef3f8',
    mutedForeground: '#60708a',
    primary: '#2563eb',
    primaryForeground: '#ffffff',
    secondary: '#e7eef8',
    secondaryForeground: '#1f3659',
    accent: '#0891b2',
    accentForeground: '#ffffff',
    border: '#d7deeb',
    card: '#ffffff',
    cardForeground: '#111827',
    ring: '#60a5fa',
    surface: '#f1f5f9',
    surfaceSoft: '#f6f8fb',
    surfaceStrong: '#ffffff',
    surfaceElevated: '#ffffff',
    surfaceHover: '#e9eff7',
    surfaceActive: '#dce8f8',
    sidebar: '#ffffff',
    topbar: '#ffffff',
    navActive: '#e6f0ff',
    navActiveForeground: '#174ea6',
    overlay: 'rgba(15, 23, 42, 0.45)',
    shadowColor: 'rgba(15, 23, 42, 0.16)',
    brandFrom: '#2563eb',
    brandTo: '#06b6d4',
    brandText: '#ffffff',
    success: '#059669',
    successForeground: '#064e3b',
    danger: '#e11d48',
    dangerForeground: '#9f1239',
    warning: '#d97706',
    info: '#0284c7',
    editorBg: '#0c1422',
    editorBg2: '#101b2f',
    editorGutter: '#7084a8',
    tones: {
      emerald: '#059669',
      violet: '#7c3aed',
      cyan: '#0891b2',
      fuchsia: '#c026d3',
      sky: '#0284c7',
      amber: '#d97706',
      rose: '#e11d48',
    },
  },
  dark: {
    appearance: 'dark',
    background: '#070a13',
    foreground: '#e7edf8',
    muted: '#111827',
    mutedForeground: '#92a2bd',
    primary: '#7dd3fc',
    primaryForeground: '#04111e',
    secondary: '#172033',
    secondaryForeground: '#dce7f8',
    accent: '#a78bfa',
    accentForeground: '#120a2a',
    border: '#263247',
    card: '#0d1322',
    cardForeground: '#edf4ff',
    ring: '#38bdf8',
    surface: '#0a1020',
    surfaceSoft: '#10182a',
    surfaceStrong: '#131d31',
    surfaceElevated: '#162137',
    surfaceHover: '#1a263d',
    surfaceActive: '#1f304e',
    sidebar: '#0a1020',
    topbar: '#0d1322',
    navActive: '#14243a',
    navActiveForeground: '#d9f4ff',
    overlay: 'rgba(2, 6, 14, 0.72)',
    shadowColor: 'rgba(0, 0, 0, 0.68)',
    brandFrom: '#38bdf8',
    brandTo: '#a78bfa',
    brandText: '#06111f',
    success: '#34d399',
    successForeground: '#bbf7d0',
    danger: '#fb7185',
    dangerForeground: '#ffe4e6',
    warning: '#fbbf24',
    info: '#38bdf8',
    editorBg: '#080f1d',
    editorBg2: '#0c1526',
    editorGutter: '#7488ad',
    tones: {
      emerald: '#34d399',
      violet: '#a78bfa',
      cyan: '#22d3ee',
      fuchsia: '#e879f9',
      sky: '#38bdf8',
      amber: '#fbbf24',
      rose: '#fb7185',
    },
  },
  signature: {
    appearance: 'dark',
    background: '#061815',
    foreground: '#ddfff5',
    muted: '#0d2a25',
    mutedForeground: '#91cfc0',
    primary: '#2dd4bf',
    primaryForeground: '#03211e',
    secondary: '#103c34',
    secondaryForeground: '#cff8ee',
    accent: '#38bdf8',
    accentForeground: '#052336',
    border: '#1c594f',
    card: '#0a211d',
    cardForeground: '#e6fff7',
    ring: '#5eead4',
    surface: '#081c18',
    surfaceSoft: '#0d2b25',
    surfaceStrong: '#103830',
    surfaceElevated: '#123f36',
    surfaceHover: '#164b40',
    surfaceActive: '#1b5b4f',
    sidebar: '#071a17',
    topbar: '#09201c',
    navActive: '#103d36',
    navActiveForeground: '#d7fff6',
    overlay: 'rgba(2, 10, 8, 0.74)',
    shadowColor: 'rgba(0, 8, 6, 0.74)',
    brandFrom: '#2dd4bf',
    brandTo: '#38bdf8',
    brandText: '#031f1d',
    success: '#34d399',
    successForeground: '#c8ffe8',
    danger: '#fb7185',
    dangerForeground: '#ffe0e5',
    warning: '#fbbf24',
    info: '#38bdf8',
    editorBg: '#071b18',
    editorBg2: '#0b2924',
    editorGutter: '#7fc7b7',
    tones: {
      emerald: '#34d399',
      violet: '#a78bfa',
      cyan: '#22d3ee',
      fuchsia: '#f472b6',
      sky: '#38bdf8',
      amber: '#fbbf24',
      rose: '#fb7185',
    },
  },
  crimson: {
    appearance: 'dark',
    background: '#18070d',
    foreground: '#ffe7ef',
    muted: '#2b1018',
    mutedForeground: '#ef9fb6',
    primary: '#fb7185',
    primaryForeground: '#320711',
    secondary: '#421520',
    secondaryForeground: '#ffd9e2',
    accent: '#f97316',
    accentForeground: '#361307',
    border: '#5a1e2c',
    card: '#230b13',
    cardForeground: '#fff0f4',
    ring: '#fb7185',
    surface: '#1f0a11',
    surfaceSoft: '#2a1019',
    surfaceStrong: '#351420',
    surfaceElevated: '#3e1725',
    surfaceHover: '#4a1b2c',
    surfaceActive: '#5a2135',
    sidebar: '#1b080f',
    topbar: '#220b13',
    navActive: '#3e1420',
    navActiveForeground: '#ffe7ef',
    overlay: 'rgba(20, 2, 8, 0.74)',
    shadowColor: 'rgba(10, 2, 5, 0.78)',
    brandFrom: '#fb7185',
    brandTo: '#f97316',
    brandText: '#330711',
    success: '#34d399',
    successForeground: '#cbffe9',
    danger: '#fecdd3',
    dangerForeground: '#ffeef0',
    warning: '#fbbf24',
    info: '#38bdf8',
    editorBg: '#1a090f',
    editorBg2: '#230c15',
    editorGutter: '#d294aa',
    tones: {
      emerald: '#34d399',
      violet: '#c4b5fd',
      cyan: '#67e8f9',
      fuchsia: '#f472b6',
      sky: '#7dd3fc',
      amber: '#fbbf24',
      rose: '#fb7185',
    },
  },
  aurora: {
    appearance: 'dark',
    background: '#041811',
    foreground: '#dcfff0',
    muted: '#0b2b20',
    mutedForeground: '#91d9bd',
    primary: '#34d399',
    primaryForeground: '#042015',
    secondary: '#103c2d',
    secondaryForeground: '#cff8e6',
    accent: '#22d3ee',
    accentForeground: '#05252d',
    border: '#1c5d48',
    card: '#082217',
    cardForeground: '#e4fff4',
    ring: '#6ee7b7',
    surface: '#071d14',
    surfaceSoft: '#0d2b1f',
    surfaceStrong: '#103929',
    surfaceElevated: '#124331',
    surfaceHover: '#164f3b',
    surfaceActive: '#1c6048',
    sidebar: '#061a12',
    topbar: '#082016',
    navActive: '#103c2d',
    navActiveForeground: '#d7ffef',
    overlay: 'rgba(2, 10, 7, 0.74)',
    shadowColor: 'rgba(0, 9, 5, 0.76)',
    brandFrom: '#34d399',
    brandTo: '#22d3ee',
    brandText: '#042015',
    success: '#6ee7b7',
    successForeground: '#d3ffec',
    danger: '#fb7185',
    dangerForeground: '#ffe2e6',
    warning: '#fbbf24',
    info: '#22d3ee',
    editorBg: '#062118',
    editorBg2: '#0a2b1f',
    editorGutter: '#87bea9',
    tones: {
      emerald: '#34d399',
      violet: '#a78bfa',
      cyan: '#22d3ee',
      fuchsia: '#f472b6',
      sky: '#38bdf8',
      amber: '#fbbf24',
      rose: '#fb7185',
    },
  },
  'electric-night': {
    appearance: 'dark',
    background: '#0a0718',
    foreground: '#f0ebff',
    muted: '#1a1230',
    mutedForeground: '#b9aee8',
    primary: '#c084fc',
    primaryForeground: '#1b0837',
    secondary: '#2a1850',
    secondaryForeground: '#eadfff',
    accent: '#f472b6',
    accentForeground: '#3a0825',
    border: '#452878',
    card: '#130d29',
    cardForeground: '#f5f0ff',
    ring: '#c084fc',
    surface: '#100a24',
    surfaceSoft: '#1a1235',
    surfaceStrong: '#241649',
    surfaceElevated: '#2b1a57',
    surfaceHover: '#332068',
    surfaceActive: '#3d277b',
    sidebar: '#0f0922',
    topbar: '#130d29',
    navActive: '#281950',
    navActiveForeground: '#f2eaff',
    overlay: 'rgba(8, 3, 20, 0.78)',
    shadowColor: 'rgba(5, 2, 16, 0.82)',
    brandFrom: '#a78bfa',
    brandTo: '#f472b6',
    brandText: '#18082f',
    success: '#34d399',
    successForeground: '#d2ffec',
    danger: '#fb7185',
    dangerForeground: '#ffe1e8',
    warning: '#fbbf24',
    info: '#7dd3fc',
    editorBg: '#12092f',
    editorBg2: '#190c3f',
    editorGutter: '#a99be6',
    tones: {
      emerald: '#34d399',
      violet: '#c4b5fd',
      cyan: '#22d3ee',
      fuchsia: '#f0abfc',
      sky: '#7dd3fc',
      amber: '#fbbf24',
      rose: '#fb7185',
    },
  },
};

function tint(color: string, amount: number, fallback = 'transparent') {
  return `color-mix(in oklab, ${color} ${amount}%, ${fallback})`;
}

function createThemeVars(theme: ThemePalette): Record<string, string> {
  return {
    '--background': theme.background,
    '--foreground': theme.foreground,
    '--muted': theme.muted,
    '--muted-foreground': theme.mutedForeground,
    '--primary': theme.primary,
    '--primary-foreground': theme.primaryForeground,
    '--secondary': theme.secondary,
    '--secondary-foreground': theme.secondaryForeground,
    '--accent': theme.accent,
    '--accent-foreground': theme.accentForeground,
    '--border': theme.border,
    '--card': theme.card,
    '--card-foreground': theme.cardForeground,
    '--ring': theme.ring,
    '--surface': theme.surface,
    '--surface-soft': theme.surfaceSoft,
    '--surface-strong': theme.surfaceStrong,
    '--surface-elevated': theme.surfaceElevated,
    '--surface-hover': theme.surfaceHover,
    '--surface-active': theme.surfaceActive,
    '--sidebar': theme.sidebar,
    '--topbar': theme.topbar,
    '--nav-active': theme.navActive,
    '--nav-active-foreground': theme.navActiveForeground,
    '--overlay': theme.overlay,
    '--shadow-color': theme.shadowColor,
    '--brand-from': theme.brandFrom,
    '--brand-to': theme.brandTo,
    '--brand-text': theme.brandText,
    '--success': theme.success,
    '--success-foreground': theme.successForeground,
    '--danger': theme.danger,
    '--danger-foreground': theme.dangerForeground,
    '--warning': theme.warning,
    '--info': theme.info,
    '--sandbox-shell-gradient-start': theme.surfaceSoft,
    '--sandbox-shell-gradient-end': theme.background,
    '--sandbox-shell-glow-1': tint(theme.primary, 18),
    '--sandbox-shell-glow-2': tint(theme.accent, 14),
    '--sandbox-surface': tint(theme.surfaceStrong, 82),
    '--sandbox-surface-soft': tint(theme.surfaceSoft, 74),
    '--sandbox-surface-strong': tint(theme.surfaceElevated, 90),
    '--sandbox-border-soft': tint(theme.border, 80),
    '--sandbox-border-strong': tint(theme.ring, 36, theme.border),
    '--sandbox-shadow': `0 28px 64px -42px ${theme.shadowColor}`,
    '--sandbox-chip-bg': tint(theme.primary, 14),
    '--sandbox-chip-fg': tint(theme.primary, 70, theme.foreground),
    '--sandbox-muted-pill-bg': tint(theme.mutedForeground, 12),
    '--sandbox-muted-pill-fg': tint(theme.mutedForeground, 82, theme.foreground),
    '--sandbox-button-bg': tint(theme.surfaceStrong, 88),
    '--sandbox-button-fg': tint(theme.foreground, 88),
    '--sandbox-button-border': tint(theme.border, 78),
    '--sandbox-button-hover-bg': tint(theme.surfaceHover, 92),
    '--sandbox-button-hover-border': tint(theme.ring, 36, theme.border),
    '--sandbox-danger-bg': tint(theme.danger, 13),
    '--sandbox-danger-fg': theme.dangerForeground,
    '--sandbox-danger-border': tint(theme.danger, 34),
    '--sandbox-danger-hover-bg': tint(theme.danger, 20),
    '--sandbox-danger-hover-border': tint(theme.danger, 50),
    '--sandbox-run-from': theme.primary,
    '--sandbox-run-to': theme.accent,
    '--sandbox-run-shadow': `0 18px 42px -26px ${tint(theme.primary, 68)}`,
    '--sandbox-overlay': theme.overlay,
    '--sandbox-panel-overlay': tint(theme.surfaceElevated, 74),
    '--sandbox-tone-emerald': theme.tones.emerald,
    '--sandbox-tone-violet': theme.tones.violet,
    '--sandbox-tone-cyan': theme.tones.cyan,
    '--sandbox-tone-fuchsia': theme.tones.fuchsia,
    '--sandbox-tone-sky': theme.tones.sky,
    '--sandbox-tone-amber': theme.tones.amber,
    '--sandbox-tone-rose': theme.tones.rose,
    '--sandbox-editor-bg': theme.editorBg,
    '--sandbox-editor-bg-2': theme.editorBg2,
    '--sandbox-editor-gutter': theme.editorGutter,
    '--sandbox-editor-active-line': tint(theme.editorGutter, 18),
    '--sandbox-editor-tooltip-bg': tint(theme.editorBg, 98, '#000000'),
    '--sandbox-editor-tooltip-border': tint(theme.editorGutter, 42),
    '--sandbox-editor-tooltip-selected': tint(theme.primary, 20),
    '--sandbox-editor-tooltip-text': theme.foreground,
    '--sandbox-editor-tooltip-muted': theme.mutedForeground,
    '--sandbox-editor-tooltip-match': theme.accent,
    '--sandbox-success-bg': tint(theme.success, 15),
    '--sandbox-success-border': tint(theme.success, 38),
    '--sandbox-success-fg': theme.successForeground,
    '--sandbox-error-bg': tint(theme.danger, 16),
    '--sandbox-error-border': tint(theme.danger, 38),
    '--sandbox-error-fg': theme.dangerForeground,
  };
}

export const THEMES: Record<ThemeMode, Record<string, string>> = {
  light: createThemeVars(palette.light),
  dark: createThemeVars(palette.dark),
  signature: createThemeVars(palette.signature),
  crimson: createThemeVars(palette.crimson),
  aurora: createThemeVars(palette.aurora),
  'electric-night': createThemeVars(palette['electric-night']),
};

export const RESOLVED_APPEARANCE: Record<ThemeMode, ResolvedAppearance> = {
  light: palette.light.appearance,
  dark: palette.dark.appearance,
  signature: palette.signature.appearance,
  crimson: palette.crimson.appearance,
  aurora: palette.aurora.appearance,
  'electric-night': palette['electric-night'].appearance,
};
